"""Single source of truth for SSA details dialog constants."""

from __future__ import annotations

HIDDEN_DETAIL_FIELDS = {"id", "derivada_de"}
SSA_NORM_CACHE_MAX_ENTRIES = 64

DERIVADAS_DIALOG_RATIO_LEFT = 24
DERIVADAS_DIALOG_RATIO_RIGHT = 76
DERIVADAS_DIALOG_MIN_HEIGHT = 640
DERIVADAS_DIALOG_DETAILS_FONT_PT = 12.0
DERIVADAS_DIALOG_TREE_FONT_PT = 12.0
DERIVADAS_DIALOG_LABEL_FONT_PT = 11.0
DERIVADAS_DIALOG_MIN_WIDTH = 960
DERIVADAS_DIALOG_TREE_MIN_WIDTH = 180
DERIVADAS_DIALOG_DETAILS_MIN_WIDTH = 520
DERIVADAS_DIALOG_GRAPH_PANEL_MIN_HEIGHT = 120
DERIVADAS_DIALOG_BOTTOM_TARGET_MIN_HEIGHT = 180

DERIVADAS_GRAPH_NODE_WIDTH = 100
DERIVADAS_GRAPH_NODE_HEIGHT = 30
DERIVADAS_GRAPH_X_GAP = 170
DERIVADAS_GRAPH_Y_GAP = 60
DERIVADAS_GRAPH_MARGIN = 8
DERIVADAS_GRAPH_MAX_DESCENDANTS = 120

DERIVADAS_SPLITTER_HANDLE_WIDTH = 10
