# gui/ssa/gui_filters_advanced.py
# Relation: used by gui/gui_ssa.py (SSAMainWindow facade).
# Relation: exposes advanced filters UI and logic via submodules.

from __future__ import annotations

from .gui_filters_advanced_logic import (
    _apply_advanced_filters,
    _build_derivadas_tree,
    _cache_token,
)
from .gui_filters_advanced_state import (
    DIVISAO_SETORES,
    MONO_FONT_FAMILY,
    SECTOR_TO_DIV,
    AdvancedFilterState,
    configure_adv_filters_constants,
)
from .gui_filters_advanced_ui import (
    _apply_advanced_filters_from_ui,
    _apply_divisao_to_setor_checks,
    _build_advanced_filters_panel,
    _clear_advanced_filters,
    _collect_divisao_setores,
    _ensure_responsavel_options_materialized,
    _get_checked_values,
    _has_active_advanced_filters,
    _make_multiselect_box,
    _mark_responsavel_dirty,
    _on_adv_sector_exclude_changed,
    _on_adv_sector_selection_changed,
    _on_macro_filter_changed,
    _on_sector_debounce_timeout,
    _parse_week,
    _refresh_advanced_filter_options,
    _refresh_priority_menus,
    _refresh_reprogramacoes_menu,
    _refresh_responsavel_options,
    _refresh_sector_menus,
    _refresh_year_menus,
    _reorganize_advanced_filters_grid,
    _run_menu_pre_show_hook,
    _save_advanced_filters_default,
    _schedule_sector_options_refresh,
    _sector_sort_key,
    _set_checkbox_checked_quietly,
    _set_menu_pre_show_hook,
    _show_derivadas_popup,
    _sort_responsavel_values,
    _sort_sectors,
    _sync_advanced_filter_ui,
    _sync_responsavel_button_summaries,
    _sync_responsavel_flags,
    _update_derivadas_button_state,
)
from .gui_filters_multiselect_menu import (
    _attach_multiselect_menu,
    _checkbox_value,
    _rebuild_multiselect_menu,
    _sync_multiselect_checks,
    _update_multiselect_button,
)

__all__ = [
    "DIVISAO_SETORES",
    "SECTOR_TO_DIV",
    "MONO_FONT_FAMILY",
    "AdvancedFilterState",
    "configure_adv_filters_constants",
    "_attach_multiselect_menu",
    "_apply_advanced_filters_from_ui",
    "_apply_divisao_to_setor_checks",
    "_apply_advanced_filters",
    "_build_derivadas_tree",
    "_build_advanced_filters_panel",
    "_checkbox_value",
    "_clear_advanced_filters",
    "_collect_divisao_setores",
    "_ensure_responsavel_options_materialized",
    "_get_checked_values",
    "_has_active_advanced_filters",
    "_make_multiselect_box",
    "_mark_responsavel_dirty",
    "_on_adv_sector_exclude_changed",
    "_on_adv_sector_selection_changed",
    "_on_macro_filter_changed",
    "_on_sector_debounce_timeout",
    "_parse_week",
    "_rebuild_multiselect_menu",
    "_refresh_advanced_filter_options",
    "_refresh_priority_menus",
    "_refresh_reprogramacoes_menu",
    "_refresh_responsavel_options",
    "_refresh_sector_menus",
    "_refresh_year_menus",
    "_reorganize_advanced_filters_grid",
    "_run_menu_pre_show_hook",
    "_save_advanced_filters_default",
    "_schedule_sector_options_refresh",
    "_sector_sort_key",
    "_set_checkbox_checked_quietly",
    "_set_menu_pre_show_hook",
    "_show_derivadas_popup",
    "_sort_responsavel_values",
    "_sort_sectors",
    "_sync_advanced_filter_ui",
    "_sync_multiselect_checks",
    "_sync_responsavel_button_summaries",
    "_sync_responsavel_flags",
    "_update_derivadas_button_state",
    "_update_multiselect_button",
    "_cache_token",
]
