engines:
  pylint:
    enabled: true
  bandit:
    enabled: true
  prospector:
    enabled: true

exclude_paths:
  - "tests/**"
  - "build/**"
  - "builds/**"
  - "dist/**"
  - "**/__pycache__/**"
  - "**/*.pyc"
