from __future__ import annotations

from typing import Dict

DEFAULT_DISPLAY_MAPPINGS: Dict[str, str] = {
    "id": "id",
    "numero_ssa": "Nº SSA",
    "situacao": "Situação",
    "derivada_de": "Derivada de",
    "localizacao_codigo": "Loc.",
    "descricao_localizacao": "Desc. Loc.",
    "equipamento": "Equip.",
    "semana_cadastro": "Sem.\nCadastro",
    "data_cadastro": "Emitida Em",
    "descricao_ssa": "Descrição da SSA",
    "setor_emissor": "Emissor",
    "setor_executor": "Executor",
    "solicitante": "Solicitante",
    "servico_origem": "Serv. Origem",
    "grau_prioridade_emissao": "Prior. Emissão",
    "grau_prioridade_planejamento": "Prior. Planej.",
    "execucao_simples": "Exec. Simples",
    "responsavel_programacao": "Resp. Prog.",
    "semana_programada": "Sem. Prog.",
    "responsavel_execucao": "Resp. Exec.",
    "descricao_execucao": "Descrição da Execução",
    "anomalia": "Anomalia",
    "sistema_origem": "Sis. Origem",
    "prazo_limite": "Prazo Limite",
    "status_execucao_prazo": "Situação do Prazo",
    "tempo_disponivel": "Tempo Disp.",
    "data_limite": "Data Limite",
    "tempo_excedido": "Tempo Excedido",
    "desde": "Desde",
    "tempo_total": "Tempo Total",
    "desde_1": "Desde (1)",
    "total_tempo_tpe_planejado": "Tempo TPE Plan.",
    "total_tempo_tpe_executada": "Tempo Total TPE Executada",
    "total_tempo_tex_planejado": "Tempo TEX Plan.",
    "total_tempo_tpo_planejado": "Tempo TPO Plan.",
    "total_horas_programadas": "Horas Prog.",
    "semana_executada": "Sem. Exec.",
    "num_reprogramacoes": "Nº Reprog.",
    "execucao_parcial": "Exec. Parcial",
    "situacao_da_parcial": "Situacao da Parcial",
    "atividade_especial": "Atividade Especial",
    "equipamento_retirado": "Equipamento Retirado",
    "sn_retirado": "SN Retirado",
    "destino": "Destino",
    "equipamento_instalado": "Equipamento Instalado",
    "sn_instalado": "SN Instalado",
    "sn_extra": "SN Extra",
    "origem": "Origem",
    "desativacao_da_localizacao": "Desativação da Localização",
    "instalacao_estimada": "Instalação Estimada",
    "executado": "Executado",
    "concluido": "Concluído",
    "total_tempo_tpo_executada": "Tempo TPO Exec.",
    "total_tempo_tex_executada": "Tempo Total TEX Executada",
    "data_inicio_programada": "Data Início Prog.",
    "data_programacao": "Data Programação",
    "data_inicio_reprogramada": "Data Início Reprog.",
    "data_reprogramacao": "Data Reprog.",
    "situacao_reprogramacao": "Situação Reprog.",
    "total_de_reprogramacoes": "Total Reprog.",
    "situacao_de_desvio": "Situação Desvio",
    "ate_1": "Até (1)",
    "ate_2": "Até (2)",
    "desde_2": "Desde (2)",
    "numero_ssa_relacionada_1": "Nº SSA Rel. 1",
    "numero_ssa_relacionada_2": "Nº SSA Rel. 2",
    "numero_ssa_relacionada_3": "Nº SSA Rel. 3",
    "setor_emissor_relacionado_1": "Setor Emissor Rel. 1",
    "setor_emissor_relacionado_2": "Setor Emissor Rel. 2",
    "setor_executor_relacionado_1": "Setor Executor Rel. 1",
    "setor_executor_relacionado_2": "Setor Executor Rel. 2",
    "situacao_relacionada_1": "Situação Rel. 1",
    "situacao_relacionada_2": "Situação Rel. 2",
    "relacao": "Relação",
}

# Column affinity score (higher means closer to left in "show all by affinity").
# Keep this as a plain map so UI flows can reuse it without layout coupling.
COLUMN_AFFINITY_SCORES: Dict[str, int] = {
    # Core identifiers
    "numero_ssa": 1000,
    "situacao": 980,
    "derivada_de": 960,
    "localizacao_codigo": 940,
    "descricao_localizacao": 930,
    "equipamento": 920,
    "descricao_ssa": 900,
    # Emissao
    "data_cadastro": 860,
    "semana_cadastro": 850,
    "solicitante": 840,
    "setor_emissor": 830,
    "grau_prioridade_emissao": 820,
    # Planejamento
    "grau_prioridade_planejamento": 780,
    "semana_programada": 770,
    "responsavel_programacao": 760,
    # Programacao
    "data_inicio_programada": 730,
    "data_programacao": 720,
    # Reprogramacao
    "num_reprogramacoes": 680,
    "total_de_reprogramacoes": 670,
    "data_inicio_reprogramada": 660,
    "data_reprogramacao": 650,
    "situacao_reprogramacao": 640,
    # Execucao
    "descricao_execucao": 600,
    "responsavel_execucao": 590,
    "semana_executada": 580,
    "execucao_simples": 570,
    "execucao_parcial": 560,
    "concluido": 550,
    "executado": 540,
}

# Default mapping used if column_mappings.json is missing/invalid
DEFAULT_COLUMN_MAPPINGS: Dict[str, list] = {
    "numero_ssa": ["Nº SSA", "Nº SSA*", "Nº SSA Original", "Numero SSA", "Nº da SSA"],
    "situacao": ["Situação", "Situacao", "Status"],
    "derivada_de": ["Derivada de", "Derivada De"],
    "localizacao_codigo": [
        "Loc.",
        "Localização",
        "Cod. Localização",
        "Codigo Localizacao",
    ],
    "descricao_localizacao": [
        "Desc. Loc.",
        "Descrição da Localização",
        "Descricao Localizacao",
    ],
    "equipamento": ["Equip.", "Equipamento"],
    "semana_cadastro": ["Sem.\nCadastro", "Sem. Cadastro", "Semana Cadastro"],
    "data_cadastro": [
        "Emitida Em",
        "Data de Emissão",
        "Data Cadastro",
        "Data/Hora de Cadastro",
    ],
    "descricao_ssa": ["Descrição da SSA", "Descricao da SSA", "Descricao"],
    "setor_emissor": ["Emissor", "Setor Emissor"],
    "setor_executor": ["Executor", "Setor Executor"],
    "solicitante": ["Solicitante"],
    "servico_origem": ["Serv. Origem", "Serviço de Origem"],
    "grau_prioridade_emissao": [
        "Prior. Emissão",
        "Prioridade Emissão",
        "Grau Prioridade Emissão",
    ],
    "grau_prioridade_planejamento": [
        "Prior. Planej.",
        "Prioridade Planejamento",
        "Grau Prioridade Planejamento",
    ],
    "execucao_simples": ["Exec. Simples", "Execução Simples"],
    "responsavel_programacao": ["Resp. Prog.", "Responsável Programação"],
    "semana_programada": ["Sem. Prog.", "Semana Programada"],
    "responsavel_execucao": ["Resp. Exec.", "Responsável Execução"],
    "descricao_execucao": ["Descrição da Execução", "Descricao da Execucao"],
    "prazo_limite": ["Prazo Limite"],
    "tempo_disponivel": ["Tempo Disp.", "Tempo Disponível"],
    "data_limite": ["Data Limite"],
    "tempo_excedido": ["Tempo Excedido"],
    "desde": ["Desde"],
    "tempo_total": ["Tempo Total"],
    "desde_1": ["Desde (1)"],
    "total_tempo_tpe_planejado": ["Tempo TPE Plan.", "Total Tempo TPE Planejado"],
    "total_tempo_tex_planejado": ["Tempo TEX Plan.", "Total Tempo TEX Planejado"],
    "total_tempo_tpo_planejado": ["Tempo TPO Plan.", "Total Tempo TPO Planejado"],
    "total_horas_programadas": ["Horas Prog.", "Total Horas Programadas"],
    "total_tempo_tpe_executada": ["Total Tempo TPE Executada"],
    "semana_executada": ["Sem. Exec.", "Semana Executada"],
    "num_reprogramacoes": ["Nº Reprog.", "Número de Reprogramações", "Reprogramações"],
    "execucao_parcial": ["Exec. Parcial", "Execução Parcial"],
    "anomalia": ["Anomalia"],
    "sistema_origem": ["Sis. Origem", "Sistema de Origem"],
    "numero_desvios": ["Número de Desvios", "Nº de Desvios", "Desvio"],
    "justificativa": ["Justificativa", "Justificativa sem APR"],
    "atividade_especial": ["Atividade Especial", "Actividad Especial"],
    "equipamento_retirado": ["Equipamento Retirado"],
    "destino": ["Destino"],
    "equipamento_instalado": ["Equipamento Instalado"],
    "origem": ["Origem"],
    "desativacao_da_localizacao": ["Desativação da localização"],
    "instalacao_estimada": ["Instalação Estimada"],
    "executado": ["Executado"],
    "concluido": ["Concluído"],
    "total_tempo_tpo_executada": ["Total Tempo TPO Executada"],
    "data_inicio_programada": ["Data início Programada"],
    "data_programacao": ["Data de programação"],
    "data_inicio_reprogramada": ["Data início Reprogramada"],
    "data_reprogramacao": ["Data de reprogramação"],
    "situacao_reprogramacao": ["Situação de Reprogramação"],
    "total_de_reprogramacoes": ["Total de Reprogramações"],
    "situacao_de_desvio": ["Situação de Desvio"],
    "relacao": ["Relação"],
    "sn": ["SN"],
    "ate_1": ["Até (1)"],
    "ate_2": ["Até (2)"],
    "desde_2": ["Desde (2)"],
    "numero_ssa_relacionada_1": ["Número da SSA Relacionada"],
    "numero_ssa_relacionada_2": ["Número da SSA Relacionada (2)"],
    "setor_emissor_relacionado_1": ["Setor Emissor Relacionado"],
    "setor_emissor_relacionado_2": ["Setor Emissor Relacionado (2)"],
    "setor_executor_relacionado_1": ["Setor Executor Relacionado"],
    "setor_executor_relacionado_2": ["Setor Executor Relacionado (2)"],
    "situacao_relacionada_1": ["Situação Relacionada"],
    "situacao_relacionada_2": ["Situação Relacionada (2)"],
    "status_execucao_prazo": ["Situação do Prazo", "Status Prazo"],
}
