"""Default search column policy for non-GUI callers."""

DEFAULT_FILTER_SEARCH_COLUMNS = (
    "numero_ssa",
    "derivada_de",
    "numero_ssa_relacionada_1",
    "numero_ssa_relacionada_2",
    "numero_ssa_relacionada_3",
    "situacao",
    "solicitante",
    "responsavel_solicitante",
    "responsavel_programacao",
    "responsavel_execucao",
    "setor_executor",
    "setor_emissor",
    "localizacao_codigo",
    "descricao_localizacao",
    "descricao_ssa",
    "descricao_execucao",
    "descricao_servico",
    "observacao",
    "grau_prioridade",
    "grau_prioridade_emissao",
    "grau_prioridade_planejamento",
    "prioridade_emissao",
    "prioridade_planejamento",
    "prazo_limite_str",
    "data_cadastro_str",
)
