"""Shared table display defaults used by GUI and config provisioning."""

from __future__ import annotations

from typing import Dict

DEFAULT_DISPLAY_MAPPINGS: Dict[str, str] = {
    "id": "id",
    "numero_ssa": "Nº SSA",
    "situacao": "Situação",
    "derivada_de": "Derivada de",
    "localizacao_codigo": "Loc.",
    "descricao_localizacao": "Desc. Loc.",
    "equipamento": "Equip.",
    "semana_cadastro": "Sem.\nCadastro",
    "data_cadastro": "Emitida Em",
    "data_planilha": "Data da Planilha",
    "deviation_records": "Deviation Records (EN)",
    "situation_of_deviation": "Situation of Deviation (EN)",
    "partial_records": "Partial Records (EN)",
    "situation_of_partial": "Situation of Partial (EN)",
    "descricao_ssa": "Descrição da SSA",
    "setor_emissor": "Emissor",
    "setor_executor": "Executor",
    "solicitante": "Solicitante",
    "servico_origem": "Serv. Origem",
    "grau_prioridade_emissao": "Prior. Emissão",
    "grau_prioridade_planejamento": "Prior. Planej.",
    "execucao_simples": "Exec. Simples",
    "responsavel_programacao": "Resp. Prog.",
    "semana_programada": "Sem. Prog.",
    "responsavel_execucao": "Resp. Exec.",
    "descricao_execucao": "Descrição da Execução",
    "anomalia": "Anomalia",
    "sistema_origem": "Sis. Origem",
    "prazo_limite": "Prazo Limite",
    "status_execucao_prazo": "Situação do Prazo",
    "tempo_disponivel": "Tempo Disp.",
    "data_limite": "Data Limite",
    "tempo_excedido": "Tempo Excedido",
    "desde": "Desde",
    "tempo_total": "Tempo Total",
    "desde_1": "Desde (1)",
    "total_tempo_tpe_planejado": "Tempo TPE Plan.",
    "total_tempo_tpe_executada": "Tempo TPE Exec.",
    "total_tempo_tex_planejado": "Tempo TEX Plan.",
    "total_tempo_tpo_planejado": "Tempo TPO Plan.",
    "total_horas_programadas": "Horas Prog.",
    "semana_executada": "Sem. Exec.",
    "num_reprogramacoes": "Nº Reprog.",
    "execucao_parcial": "Exec. Parcial",
    "situacao_da_parcial": "Situacao da Parcial",
    "atividade_especial": "Atividade Especial",
    "equipamento_retirado": "Equipamento Retirado",
    "sn_retirado": "SN Retirado",
    "destino": "Destino",
    "equipamento_instalado": "Equipamento Instalado",
    "sn_instalado": "SN Instalado",
    "sn_extra": "SN Extra",
    "origem": "Origem",
    "desativacao_da_localizacao": "Desativação da Localização",
    "instalacao_estimada": "Instalação Estimada",
    "executado": "Executado",
    "concluido": "Concluído",
    "total_tempo_tpo_executada": "Tempo TPO Exec.",
    "total_tempo_tex_executada": "Tempo TEX Exec.",
    "data_inicio_programada": "Data Início Prog.",
    "data_programacao": "Data Programação",
    "data_inicio_reprogramada": "Data Início Reprog.",
    "data_reprogramacao": "Data Reprog.",
    "situacao_reprogramacao": "Situação Reprog.",
    "total_de_reprogramacoes": "Total Reprog.",
    "situacao_de_desvio": "Situação Desvio",
    "ate_1": "Até (1)",
    "ate_2": "Até (2)",
    "desde_2": "Desde (2)",
    "numero_ssa_relacionada_1": "Nº SSA Rel. 1",
    "numero_ssa_relacionada_2": "Nº SSA Rel. 2",
    "numero_ssa_relacionada_3": "Nº SSA Rel. 3",
    "setor_emissor_relacionado_1": "Setor Emissor Rel. 1",
    "setor_emissor_relacionado_2": "Setor Emissor Rel. 2",
    "setor_executor_relacionado_1": "Setor Executor Rel. 1",
    "setor_executor_relacionado_2": "Setor Executor Rel. 2",
    "situacao_relacionada_1": "Situação Rel. 1",
    "situacao_relacionada_2": "Situação Rel. 2",
    "relacao": "Relação",
}

COLUMN_AFFINITY_SCORES: Dict[str, int] = {
    "numero_ssa": 1000,
    "situacao": 980,
    "derivada_de": 960,
    "localizacao_codigo": 940,
    "descricao_localizacao": 930,
    "equipamento": 920,
    "descricao_ssa": 900,
    "data_cadastro": 860,
    "semana_cadastro": 850,
    "solicitante": 840,
    "setor_emissor": 830,
    "grau_prioridade_emissao": 820,
    "grau_prioridade_planejamento": 780,
    "semana_programada": 770,
    "responsavel_programacao": 760,
    "data_inicio_programada": 730,
    "data_programacao": 720,
    "num_reprogramacoes": 680,
    "total_de_reprogramacoes": 670,
    "data_inicio_reprogramada": 660,
    "data_reprogramacao": 650,
    "situacao_reprogramacao": 640,
    "descricao_execucao": 600,
    "responsavel_execucao": 590,
    "semana_executada": 580,
    "status_execucao_prazo": 575,
    "execucao_simples": 570,
    "execucao_parcial": 560,
    "concluido": 550,
    "executado": 540,
    "atividade_especial": 530,
}
